version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: workindia
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data