CREATE TABLE "book" (
  "book_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "author" varchar,
  "isbn" integer
);

CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL
);

CREATE TABLE "issue" (
  "issue_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "issue_time" datetime NOT NULL,
  "return_time" datetime NOT NULL
);

ALTER TABLE "issue" ADD FOREIGN KEY ("book_id") REFERENCES "book" ("book_id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "users" ADD FOREIGN KEY ("user_id") REFERENCES "issue" ("user_id") ON DELETE CASCADE ON UPDATE NO ACTION;
